### PR TITLE
Fixes backspace handling and button navigation

### LINKED ISSUE #40: Prevent "backspace" in input fields to pop history
Currently when developing now and using input field with keyboard, a 'backspace' press will pop history and "go back".

### LINKED ISSUE #59: Keep wallet account in sync with wallet state
Comment from #56 

When receiving funds and updating the wallet with the update button, the amount in the top doesn't get updates, but the transactions does

### PR DESCRIPTION
**Pull request by mehlium**
Fixes #40 and fixes #59 

This addresses the issue with backspace, and fixes using button keys to navigate in an input field. Also moves away from combining wallet + navigation state to two independent stores/states. This makes it easier to keep track of updated wallet and avoids messing with patching navigation state.

* Adds a few helper functions in Navigation in order to detect that this is an input field, and when to allow backspace to pop view
* Sets 'unlock' as default view so that it's not possible to backspace
* Removes the intermediate "QR/address" step and replaces with actual state

### CODE REVIEW

**Comment by Citrullin** [comment]
I only get a white screen on my phone. No errors at all. Need to figure out why this is happening later.

**Comment by mehlium** [comment]
This device :see_no_evil: Perhaps manually deleting first helps on the issue.

**Comment by Citrullin** [comment]
> 
> 
> This device 🙈 Perhaps manually deleting first helps on the issue.

I already did that... So, I guess this is not happening to you?

**Comment by Citrullin** [comment]
Ohh shit, sorry, layer 8. I was using autocomplete and used the wrong branch. Maybe I should start deleting some branches ^^

**Comment by Citrullin** [comment]
Not sure, if there are already issues for it. I just write it down:
- Would be nice to have a loading icon when creating the seed. Not sure, if it is possible, because the crypto is taking the full processor capacity. 
- When I am in the transaction history, update and get a tx added and go back, the state isn't updated. 
- Scrolling in the menu doesn't work.
- Use-case: User goes into settings, but it was the wrong menu item. User wants to go back, but isn't able to, because back deletes in input. Maybe use back button as back when user hasn't used the right button yet or didn't typed in a character. 
Probably something for @rtaibah to think about, I guess.

**Comment by mehlium** [comment]
Thanks for testing, added two issues for the first two points (#64 and #65). Scrolling is an issue all over and will make an issue for that as well.

For the last point, not focusing element when we step in to a new view would solve that? So a user first has to press "down" to select the input element.

**Pull request merged**
