### PR TITLE
Added Russian language

### PR DESCRIPTION
**Pull request by 8kbh**
In some places, the text on the buttons does not fit. I fixed it myself using the following code
```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```
image

### CODE REVIEW

**Comment by mehlium** [comment]
W00t, thank you so much for this contribution! Will have a look at it soon!

**Comment by mehlium** [comment]
@Rtif173 do you mind me adding you as contributor under https://github.com/Kaiak/kaiak-wallet/blob/master/README.md#translating ?

**Comment by 8kbh** [comment]
@aspic Sure, go ahead

**Review by mehlium — APPROVED** [review]
LGTM, thanks for the contribution!

**Pull request merged**
